---
- name: "Add repo for RedHat"
  block:
    - name: "import docker gpg key"
      ansible.builtin.rpm_key:
        key: "{{ docker_const[ansible_os_family]['docker_gpg'] }}"
        state: present

    - name: "add docker repository"
      ansible.builtin.yum_repository:
        name: docker
        description: docker YUM repo
        baseurl: "{{ docker_const[ansible_os_family]['docker_repo'] }}"
        gpgcheck: yes
        enabled: true
        gpgkey: "{{ docker_const[ansible_os_family]['docker_gpg'] }}"
        module_hotfixes: true
  when: docker.repo == "third_party"

- name: install docker packages.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_const[ansible_os_family]['packages'] }}"